### ISSUE TITLE
Requesting to Join

### ISSUE THREAD

**Issue by mrxinu** [CrowdStrike/community#40]
Per [the policy here](https://opensource.crowdstrike.com/open-source-policy/), I'm submitting this user for access! 👋  My username on the internal Slack is also 'mrxinu'.

**Comment by shawndwells** [comment]
No problem. It's a holiday in the US. Will connect tomorrow.

**Comment by shawndwells** [comment]
Reached out to @mrxinu on internal slack and confirmed request. Added to CrowdStrike org as general user. 

Welcome, @mrxinu! 🍻
