### ISSUE TITLE
Request to join CrowdStrike GitHub Organization

### ISSUE THREAD

**Issue by kim-brown** [CrowdStrike/community#44]
Hi,

Following the steps outlined [here](https://opensource.crowdstrike.com/open-source-policy/#engineering), I wanted to confirm my identity as a CrowdStrike engineer since I am planning on contributing a script in the near future. My email's kim.brown@crowdstrike.com and my full name is Kim Brown.

Thanks!
-Kim

**Comment by shawndwells** [comment]
Verified on in internal slack. Welcome, @kim-brown 👋 

Added to the overall CrowdStrike GitHub org. Many projects have their own repo-level permissions, so you may need to reach out to would-be collaborators for permissions like merge access.
