### ISSUE TITLE
Running services in Linux

### ISSUE THREAD

**Issue by alpana17** [CrowdStrike/community#51]
How to check running services in Linux machine?
I can see running services for Windows.

**Comment by jshcodes** [comment]
Hi @alpana17 -

I believe your question is "how do I confirm the CrowdStrike agent is running on a Linux machine"?

This can be accomplished by executing one of the following commands (depending on your Linux environment):

```shell
service falcon-sensor status
```
or
```shell
systemctl status falcon-sensor
```

Please re-open this issue if I've not answered the correct question. :smile:

**Comment by shawndwells** [comment]
Hi @alpana17 - since this is a product support question, please open a ticket at https://supportportal.crowdstrike.com/ . The folks there will be better able to help with general falcon console questions!
