### ISSUE TITLE
Add Zoë to the org

### ISSUE THREAD

**Issue by ZoeBijl** [CrowdStrike/community#52]
Hello, I’d like to be added to the org.

Name: Zoë Bijl
Function: Falcon Accessibility Lead
Email: zoe.bijl

**Comment by shawndwells** [comment]
Verified on internal slack. Welcome, @ZoeBijl! 👋 

Added you to the CrowdStrike GitHub org. Many projects have their own repo-level permissions, e.g. for merge access, which means you might need to ping your repo-level collaborators for further accesses.
