### ISSUE TITLE
Request to be added to this repo

### ISSUE THREAD

**Issue by ryhinchey** [CrowdStrike/community#54]
Hi there! 

I would like to join this group. Here are the details:

Name: Ryan Hinchey
Email: ryan.hinchey@crowdstrike.com

Thanks,

Ryan

**Comment by shawndwells** [comment]
Verified on internal systems & added. Welcome, @ryhinchey :) 

Note many projects have per-repo permissions. If you're collaborating on an existing project, you may need to ping would-be collaborators. They can add you into repo-level merge access.
