### ISSUE TITLE
BOSH-release for Falcon

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/community#6]
Is there any plan in the pipeline to create a BOSH-release for Falcon?

**Comment by aghassemlouei** [comment]
Dropping a note that the following repository may be a good starting point: 

https://github.com/rahulkj/crowdstrike-boshrelease

**Comment by redhatrises** [comment]
Please see https://github.com/crowdstrike/falcon-boshrelease for VMWare TAS support.
