### ISSUE TITLE
ERROR 400: Bad Request

### ISSUE THREAD

**Issue by umeshkumare05** [CrowdStrike/community#74]
While using wget command to check the connectivity we are getting  error

wget --no-check-certificate --method POST  --timeout=0 --header 'Authorization: Basic ODc4MTM1Zjzg4Mzc4NTQ3MTZkYWI2Nzg6N2FucZHazlMMWhJTlRpMzBGSFFBODVXc0tDMkJ0elhPZmN3RQ' --header 'Content-Type: application/x-www-form-urlencoded' 'https://api.crowdstrike.com/oauth2/token'
--2024-03-11 02:23:15--  https://api.crowdstrike.com/oauth2/token
Resolving [api.crowdstrike.com](http://api.crowdstrike.com/) ([api.crowdstrike.com](http://api.crowdstrike.com/))... 54.241.246.108, 13.56.9.61
Connecting to [api.crowdstrike.com](http://api.crowdstrike.com/) ([api.crowdstrike.com](http://api.crowdstrike.com/))|54.241.246.108|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2024-03-11 02:23:15 ERROR 400: Bad Request.

**Comment by redhatrises** [comment]
You need to use the following replacing MYCLIENTID and MYCLIENTSECRET with the correct OAUTH values, and in general, should use curl over wget:

```
wget --no-check-certificate --timeout=0 --header 'Content-Type: application/x-www-form-urlencoded' 'https://api.crowdstrike.com/oauth2/token' --post-data "client_id=MYCLIENTID&client_secret=MYCLIENTSECRET"
```

**Comment by redhatrises** [comment]
Closing this as there has been no further movement. Please re-open if needed.
