### ISSUE TITLE
Add feature to RTR containment policy

### ISSUE THREAD

**Issue by PaulSocker** [CrowdStrike/community#75]
Issue:  Containment policies allow for whitelisted network access to IP addresses but not domains.

Crowdstrike is our primary EDR tool, we use it to perform containment operations.  One thing we would like to do is update the containment policy.  We use some tools that automatically send data to Amazon S3 buckets.  S3 buckets do not have IP addresses so we cant add them to our whitelist in the containment policy.

Could we add functionality that would allow the addition of domains to the network whitelist in containment policies.

**Comment by redhatrises** [comment]
Hello,

Thank you for opening this ticket. This repo is more for open source community related things than for requesting enhancements to products. Please open an idea in the crowdstrike console to request this feature.
