### ISSUE TITLE
crowdstrike bypasses latest program reporting

### ISSUE THREAD

**Issue by VulnerabilityReporting** [CrowdStrike/community#76]
Hello, the attacker used a new technique to bypass CrowdStrike, as customers and users hope to update the generic countermeasures as soon as possible to stop his bypass!
https://github.com/helviojunior/hookchain

**Comment by redhatrises** [comment]
This isn't the place to report these kind of issues. Please reach out to [bugs@crowdstrike.com](mailto:bugs@crowdstrike.com)
