### ISSUE TITLE
Create website of projects

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/community#8]
We should create a website of projects that are linked from here in addition to contribution guidelines, etc.

**Comment by shawndwells** [comment]
Love it!

@redhatrises and I had a chance to chat direct about this. Bringing those conversational notes here, we spoke of something similar in function to https://code.nsa.gov/ (code: https://github.com/NationalSecurityAgency/nationalsecurityagency.github.io), but perhaps CrowdStrike branded.

Key theme being list all the projects CrowdStrike contributes to. Even (especially!) those outside the CrowdStrike org such as Kafka.

**Comment by shawndwells** [comment]
/me tosses in vote to fork the NSA repo and tailor it =P

**Comment by redhatrises** [comment]
https://github.com/CrowdStrike/community/pull/9 implements this. Closing
